// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmvzzwaecoeigpvwhnfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtdnp6d2FlY29laWdwdndobmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDU0ODksImV4cCI6MjA3MTEyMTQ4OX0.n91jhAKR0Z3GawrTp9JZ59dAmS6IS8dYdzDT3fOJ_gE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});